name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check style
        run: composer test:lint

      - name: Check types
        run: composer test:types

      - name: Run test suite
        run: vendor/bin/pest --coverage --coverage-clover=coverage.xml

      -   name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
